2013-03-30 04:32:29 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:32:29 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:34:27 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:34:27 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:34:29 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:34:29 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:35:09 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:35:09 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:35:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:35:12 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:35:14 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:35:14 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:36:23 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:36:23 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:39:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:39:33 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:40:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:40:53 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:40:54 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:40:54 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:40:56 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:40:56 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:42:17 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 04:42:17 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:46:53 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:46:53 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:47:12 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:47:12 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:47:22 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:47:22 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:49:04 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:49:04 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:49:49 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:49:49 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:50:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:50:32 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:50:40 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:50:40 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:50:43 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:50:43 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:51:09 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:51:09 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:51:40 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:51:40 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 04:53:21 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 56]
2013-03-30 04:53:21 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 56, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 05:01:04 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 05:01:04 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 05:02:37 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 55]
2013-03-30 05:02:37 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 55, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 05:05:30 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 57]
2013-03-30 05:05:30 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 57)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 57, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 57, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 05:15:49 Error: Fatal Error (1): Call to a member function create() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 42]
2013-03-30 05:15:49 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 42, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 42, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 05:16:10 Error: Fatal Error (1): Call to a member function create() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 42]
2013-03-30 05:16:10 Error: [FatalErrorException] Call to a member function create() on a non-object
Request URL: /accounts/add
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 42)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 42, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 42, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:47:01 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:47:01 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:47:41 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:47:41 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:48:04 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:48:04 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:48:15 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:48:15 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:50:50 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:50:50 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:50:58 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:50:58 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:53:24 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:53:24 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:53:45 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:53:45 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:55:39 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:55:39 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:58:07 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:58:07 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:58:44 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:58:44 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 08:58:45 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 08:58:45 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:01:05 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:01:05 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:01:28 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:01:28 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:01:30 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:01:30 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:01:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:01:33 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:01:35 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:01:35 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:07:14 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:07:14 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:14:44 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:14:44 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:25:41 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:25:41 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:27:46 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:27:46 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:31:33 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:31:33 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:31:37 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:31:37 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:32:48 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 17]
2013-03-30 09:32:48 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 17, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:47:44 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Fee.id' in 'where clause'
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\school_erp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Account...', Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Model\Datasource\DboSource.php(670): DboSource->execute('SELECT `Account...', Array, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Model\Datasource\DboSource.php(1081): DboSource->fetchAll('SELECT `Account...', false)
#4 D:\xampp\htdocs\school_erp\lib\Cake\Model\Model.php(2688): DboSource->read(Object(AppModel), Array)
#5 D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php(18): Model->find('first', Array)
#6 [internal function]: AccountsController->index()
#7 D:\xampp\htdocs\school_erp\lib\Cake\Controller\Controller.php(486): ReflectionMethod->invokeArgs(Object(AccountsController), Array)
#8 D:\xampp\htdocs\school_erp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#9 D:\xampp\htdocs\school_erp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(AccountsController), Object(CakeRequest), Object(CakeResponse))
#10 D:\xampp\htdocs\school_erp\app\webroot\index.php(109): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
2013-03-30 09:47:59 Error: Fatal Error (1): Call to a member function find() on a non-object in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 18]
2013-03-30 09:47:59 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 18, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 18, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-03-30 09:58:15 Error: Fatal Error (4): syntax error, unexpected '$options' (T_VARIABLE) in [D:\xampp\htdocs\school_erp\app\Controller\AccountsController.php, line 18]
2013-03-30 09:58:15 Error: [FatalErrorException] syntax error, unexpected '$options' (T_VARIABLE)
Request URL: /accounts
Stack Trace:
#0 D:\xampp\htdocs\school_erp\lib\Cake\Error\ErrorHandler.php(184): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 18)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 18, Array)
#2 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(927): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 18, Array)
#3 D:\xampp\htdocs\school_erp\lib\Cake\Core\App.php(900): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
